name = "DACE"
uuid = "f4439622-e757-4457-9ca0-f65a61d23f40"
authors = ["Chris Scott <chris.scott@nesi.org.nz>"]
version = "0.1.0"

[deps]
DACE_jll = "40de70a5-cf80-53d9-bda4-3aa67fea2f4f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
