name = "DACE"
uuid = "f4439622-e757-4457-9ca0-f65a61d23f40"
authors = ["Chris Scott <chris.scott@nesi.org.nz>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
DACE_jll = "40de70a5-cf80-53d9-bda4-3aa67fea2f4f"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
julia = "1.6"
CxxWrap = "~0.16"
DACE_jll = "~0.5"
DiffEqBase = "^6"
SpecialFunctions = "^2"
DocStringExtensions = "^0.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
